language: node_js

node_js:
  - "10"
  - "9"
  - "8"

install:
  - npm install -g codecov istanbul
  - npm install

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
  - codecov
